name: docs
concurrency: docs

on: [push]

jobs:
  docs:
    name: HOPES documentation
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install docs requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
